# Generated by Django 5.0.7 on 2024-07-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_hodimlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodimlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
