# Generated by Django 5.0.7 on 2024-07-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel_nomer', models.IntegerField()),
                ('murojaat', models.TextField()),
                ('vaqti', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
